services:
  AvitOffdb:
    image: postgres:17
    container_name: AvitOffdb
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: AvitOffdb
    networks:
      - service_net
    restart: on-failure

  service:
    build: .
    ports:
      - "${PORT}:8000"
    environment:
      DATABASE_URL: "postgresql://dbuser:dbpassword@AvitOffdb:5432/AvitOffdb"
      PORT: 8080
      SECRET_KEY: abouba
    depends_on:
      - AvitOffdb
    networks:
      - service_net
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.50"
    restart: on-failure

networks:
  service_net:
    driver: bridge
